# Generated by Django 4.1 on 2022-08-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
