# Generated by Django 4.1 on 2022-08-14 04:14

import contextlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0020_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=contextlib.nullcontext, upload_to='uploads\\products'),
        ),
    ]
