# Generated by Django 4.1 on 2022-08-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0021_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
