# Generated by Django 4.1 on 2022-08-14 12:52

import contextlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0022_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=contextlib.nullcontext),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(default=contextlib.nullcontext, max_length=6),
        ),
    ]
