# Generated by Django 4.1 on 2022-08-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0023_customer_address_customer_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
