# Generated by Django 4.1 on 2022-08-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0025_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
