# Generated by Django 4.1 on 2022-08-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0026_remove_cart_category_delete_table_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
