# Generated by Django 4.1 on 2022-08-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0027_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
