# Generated by Django 4.1 on 2022-12-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0032_order_delete_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='MRP',
        ),
    ]
