# Generated by Django 4.1 on 2022-12-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0034_product_discount_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='productfullname',
        ),
    ]
