# Generated by Django 4.1 on 2022-12-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0035_rename_description_product_productfullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
