# Generated by Django 4.1 on 2022-12-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0039_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='product',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
