# Generated by Django 4.1 on 2022-12-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0040_alter_order_item_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='product',
            new_name='productids',
        ),
    ]
