# Generated by Django 4.1 on 2022-12-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0041_rename_product_order_item_productids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MRP',
            field=models.IntegerField(),
        ),
    ]
