# Generated by Django 4.1 on 2022-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0042_alter_product_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
