# Generated by Django 4.1 on 2022-12-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0044_ordered_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='status',
            new_name='deliverystatus',
        ),
        migrations.AddField(
            model_name='order_item',
            name='outofdeliverystatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_item',
            name='shippingstatus',
            field=models.BooleanField(default=False),
        ),
    ]
