# Generated by Django 4.1 on 2022-12-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0045_rename_status_order_item_deliverystatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='deliverystatus',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='outofdeliverystatus',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='shippingstatus',
        ),
        migrations.AddField(
            model_name='order_item',
            name='status',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=128),
        ),
    ]
