# Generated by Django 4.1 on 2022-12-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0046_remove_order_item_deliverystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='status',
            field=models.CharField(choices=[('S', 'Shipped'), ('O', 'OutofDelivery'), ('D', 'Delivered')], default='', max_length=128),
        ),
    ]
